### ISSUE TITLE
Where do I find "shells/chrome"?

### ISSUE THREAD

**Issue by pbastowski** [MiCottOn/DejaVue#31]
Hi Guys

I am trying to add this plugin to Chrome by following the 6 steps in the README. 1 to 5 worked as expected but step 6 doesn't.
    
> 6. Click "load unpacked extension", and choose shells/chrome.

When I click "load unpacked extension" I see no shells/chrome folder. Is it supposed to have been built in step 3?

Thanks

Paul

**Comment by sschwartz0** [comment]
Hey Paul,

Choose the entire root folder for now. Thanks for pointing this out!

Best,
MiCottOn
