### ISSUE TITLE
Component Graph doesn't expand to full width of devtools window

### ISSUE THREAD

**Issue by NickHurst** [MiCottOn/DejaVue#38]
I apologize if this is some sort of limitation I'm unaware of, however the component graph doesn't expand the full width of the window.

![screen shot 2017-02-09 at 8 30 53 pm](https://cloud.githubusercontent.com/assets/7860316/22810474/03294aaa-ef07-11e6-9eed-33c6113f0996.png)

Chrome 55.0.2883.95 (64-bit)
macOS 10.12.3

Let me know if more info is needed. Otherwise, great tool keep up the good work.

**Comment by madebymtr** [comment]
thanks nick, we will get right on it!

**Comment by sschwartz0** [comment]
Hey Nick - just uploaded the fix for this. Thanks for letting us know.
