### ISSUE TITLE
Component Inspector display issue

### ISSUE THREAD

**Issue by fajaryanw** [MiCottOn/DejaVue#41]
I have props 23, when display with component inspector, the last four props outside the dark background box. 

![1](https://cloud.githubusercontent.com/assets/6999559/22817645/16542eda-ef9b-11e6-953c-cfedb1572413.png)

**Comment by madebymtr** [comment]
thanks for bringing that to our attention @fajaryanw - this is a css bug on our part. I am in the process of working on the application UI, and this fix will be a part of the rollout later today (we are GMT-8 over here)
