### ISSUE TITLE
Will there be a Firefox version?

### ISSUE THREAD

**Issue by serge1peshcoff** [MiCottOn/DejaVue#42]
I think I'm not the only one here using Firefox instead of Chrome, it would be really nice to have a Firefox version.

**Comment by sschwartz0** [comment]
We will definitely be taking a look at porting this over to Firefox once we've squashed some more bugs!

**Comment by kimhjona** [comment]
Hi @serge1peshcoff, we unfortunately won't be able to prioritize a firefox version right now. Still working on getting our Chrome version working smoothly.
