### ISSUE TITLE
String values not closed properly in `Changes` (and propably wrong elements shown?)

### ISSUE THREAD

**Issue by Uriziel01** [MiCottOn/DejaVue#48]
### Reproduction:
change string property of component, open list of props in DejaVue inspector, go to `Changes` section.
### Result
1. Changes of string values are beggining with a `"` character, but there is no matching closing character.
2. Shouldn't the first value be name of my prop?
In my case:
```
Close modal33 changed from "Close modal2 to "Close modal
```

### Expected result:
```
`title` changed from "Close modal2" to "Close modal"
```

**Comment by sschwartz0** [comment]
Fixed, thanks!
