### ISSUE TITLE
HTML tags are not escaped inside of inspector

### ISSUE THREAD

**Issue by Uriziel01** [MiCottOn/DejaVue#53]
### Reproduction:
Create a property with string content of `<p>test1</p><pre style="background:red">test2</pre>`. Open components props in DejaVue component inspector.

### Result
`test2` is styled differently because its parsed with the HTML/style tags.

### Expected result:
All HTML tags should be escapped.

### Notes:
Same applies for `Vars` and `Changes`

**Comment by sschwartz0** [comment]
Fixed! Thanks again
