### ISSUE TITLE
Props beggining with '_' character are not displayed in inspector

### ISSUE THREAD

**Issue by Uriziel01** [MiCottOn/DejaVue#55]
### Reproduction:
Create a component property as 
```js
_options: [Array, Object]
```
 then open props list from that component inside of component inspector.

### Result
The property is not listed

### Expected result:
Property should be listed.

**Comment by sschwartz0** [comment]
This has been fixed along with the proper placement of props and vars/return data. Thanks for pointing these and other bugs out! Really appreciate it :)
