### ISSUE TITLE
Please remove console.log output

### ISSUE THREAD

**Issue by rottmann** [MiCottOn/DejaVue#62]
or add an option to view the console.log data.

e.g.
```
// run each component through the DVconstructor
                                        console.log('components', components)
```

```
                                let methodKeys = Object.keys(node).filter((el) => {
                                    if(el[0] === '_' || el[0] === '$') return false
                                    else if(typeof node[el] === 'function') return true;
                                    else return false;
                                })

                                console.log(methodKeys)
```

**Comment by bomb1e** [comment]
Yes please

**Comment by kimhjona** [comment]
hi rottmann,
console.logs have been removed!

**Comment by ffxsam** [comment]
@kimhjona Have they though? I'm still seeing stuff littered in the console..

![pasted image at 2017_09_14 01_40 pm](https://user-images.githubusercontent.com/12532733/30447727-862cc45e-9952-11e7-83fe-1c0d3a68987d.png)

**Comment by willvincent** [comment]
@kimhjona It looks like building and manually installing from the repo here works without all the console vomit, but the version available in the chrome store doesn't include that change.

Can we get an updated version published to the chrome store?

**Comment by sschwartz0** [comment]
Hey guys! You've inspired us to start doing some major updates to the project. I fixed the props issue the other day and will upload a new version to the store tonight that also includes the console log fix. Expect this to keep becoming more useful and performant and keep the suggestions coming
